ARG BASE_TAG=local
FROM wazoplatform/wazo-confgend:$BASE_TAG

# add back source code and install over version "compiled" in base image.
COPY . /usr/local/src/wazo-confgend
WORKDIR /usr/local/src/wazo-confgend
ENV PYTHONDONTWRITEBYTECODE='true'

RUN python setup.py develop

CMD ["/opt/venv/bin/wazo-confgend"]
