ARG BASE_TAG=local
FROM wazoplatform/wazo-confgend:$BASE_TAG
ARG WAZO_CONFGEND_CLIENT_REV=master

# get wazo-confgen client binary from repo.
ADD --chmod=700 https://raw.githubusercontent.com/wazo-platform/wazo-confgend-client/$WAZO_CONFGEND_CLIENT_REV/bin/wazo-confgen /usr/local/bin/wazo-confgen

# add back source code and install over version "compiled" in base image.
COPY . /usr/local/src/wazo-confgend
WORKDIR /usr/local/src/wazo-confgend
RUN python setup.py develop
ENV PYTHONDONTWRITEBYTECODE='true'

CMD ["/opt/venv/bin/wazo-confgend"]
